apiVersion: v1
kind: ServiceAccount
metadata:
  name: i-service-account
  namespace: i-prod
  annotations:
    # This links your Kubernetes pod directly to your secure AWS IAM Role
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/i-prod-secrets-role
